version: 2.1
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              sudo apt-get -y install wget zip unzip
      - run:
          name: Download Godot 3.2
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_linux_headless.64.zip
              unzip Godot_v3.2-stable_linux_headless.64.zip
              mv Godot_v3.2-stable_linux_headless.64 godot
              chmod +x godot
      - run:
          name: Download Godot 3.2 Export Templates
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_export_templates.tpz
              mkdir -p ~/.local/share/godot/templates
              unzip Godot_v3.2-stable_export_templates.tpz -d ~/.local/share/godot/templates
              mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.2.stable
      - run:
          name: Export win64 build
          command: |
              mkdir -p win64
              ./godot --export win64 project.godot "win64/Oasis Client.exe"
              zip win64 win64/*
      - store_artifacts:
          path: win64.zip
      - run:
          name: Export linux build
          command: |
              mkdir -p linux64
              ./godot --export linux project.godot "linux64/oasis-client"
              zip linux64 linux64/*
      - store_artifacts:
          path: linux64.zip
      - run:
          name: Export mac build
          command: |
              ./godot --export macOS project.godot "oasis-client-mac"
              mv oasis-client-mac macOS.zip
              ls
      - store_artifacts:
          path: macOS.zip
